apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-app-dpl
  namespace: stg
  labels:
    #Project ID
    app: mc-app
spec:
  #Run one instances of our application
  replicas: 1
  selector:
    matchLabels:
      app: mc-app-pod
  template:
    metadata:
      labels:
        app: mc-app-pod
    spec:
      #Container details
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      containers:
        - name: mc-app
          image: gcr.io/bytegum/mc-app:latest
          imagePullPolicy: Always
          #Ports to expose
          ports:
            - containerPort: 7000
              protocol: TCP
          env:
            - name: API_URL
              value: http://$(MC_SERVICE_SRV_SERVICE_HOST):$(MC_SERVICE_SRV_SERVICE_PORT)/v1
